'use strict';
const paths={home:'<path d="m3 10 9-7 9 7v10H4V10M9 21v-8h6v8"/>',play:'<path d="m8 4 12 8-12 8Z"/>',pause:'<path d="M8 4v16M16 4v16" stroke-width="4"/>',prev:'<path d="m18 5-10 7 10 7ZM5 5v14"/>',next:'<path d="m6 5 10 7-10 7ZM19 5v14"/>',list:'<path d="M8 5h13M8 12h13M8 19h13M3 5h.1M3 12h.1M3 19h.1"/>',heart:'<path d="M20 5a5 5 0 0 0-7 0l-1 1-1-1a5 5 0 0 0-7 7l8 9 8-9a5 5 0 0 0 0-7Z"/>',settings:'<circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/><path d="M12 2v4m0 12v4M2 12h4m12 0h4M5 5l3 3m8 8 3 3M5 19l3-3m8-8 3-3"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',music:'<path d="M9 18V5l11-2v13M9 8l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',left:'<path d="m15 5-7 7 7 7"/>',right:'<path d="m9 5 7 7-7 7"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',grip:'<path d="M4 6h16M4 12h16M4 18h16"/>',order:'<path d="M3 7h18m-4-4 4 4-4 4M3 17h18m-4-4 4 4-4 4"/>',shuffle:'<path d="M3 5h3c5 0 7 14 12 14h3m-4-4 4 4-4 3M3 19h3c5 0 7-14 12-14h3m-4-3 4 3-4 4"/>',repeat:'<path d="M20 7A9 9 0 0 0 5 5L3 8M3 3v5h5M4 17a9 9 0 0 0 15 2l2-3m-5 0h5v5"/>',single:'<path d="M20 7A9 9 0 0 0 5 5L3 8M3 3v5h5M4 17a9 9 0 0 0 15 2l2-3m-5 0h5v5M10 10l2-1v6m-2 0h4"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',qr:'<path d="M3 3h6v6H3Zm12 0h6v6h-6ZM3 15h6v6H3Zm12 0h3v3h3v3h-6Zm6-3v3M12 3v9H3m9 3v6"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.music}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ib=(iconName,action,label,cls='')=>`<button class="icon ${cls}" data-action="${action}" aria-label="${label}">${icon(iconName)}</button>`;
const pages=[['home','首页','home'],['playing','正在播放','play'],['playlists','歌单列表','list'],['favorites','我的收藏','heart'],['settings','系统设置','settings'],['search','全网搜索','search'],['local','本地音乐','music'],['downloads','下载管理','download']];
const tracks=[{name:'晚风心里吹',artist:'阿梨粤',cover:'coast'},{name:'夜空中最亮的星',artist:'逃跑计划',cover:'moon'},{name:'有何不可',artist:'许嵩',cover:'forest'},{name:'这世界那么多人',artist:'莫文蔚',cover:'city'},{name:'一路向北',artist:'周杰伦',cover:'sunset'}];
const groups=[['我喜欢的音乐','APP 收藏','moon'],['日常循环','我的歌单','city'],['静静听一会','精选歌单','forest'],['慢慢醒来','精选歌单','morning'],['向海边出发','精选歌单','coast']];
const state={query:'',page:'home',current:0,playing:false,progress:38,mode:0,favorites:new Set([0,1]),queue:[0,1,2,3,4],platform:'本地歌单',section:'播放与显示',multi:false,theme:'system'};
const art=name=>`../portrait-v1/assets/${name}.svg`,current=()=>tracks[state.current],time=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
function toast(message){const el=document.getElementById('notice');el.textContent=message;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',2200)}
function modal(title,content){document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-content').innerHTML=content;document.getElementById('dialog').showModal()}
function close(){document.getElementById('dialog').close()}
function home(){const s=current();return `<div class="home"><div class="welcome"><h2>让好音乐，随心而听。</h2><p>发现喜欢的旋律，收藏每一刻心情</p></div><section class="card hero"><img src="${art(s.cover)}" alt="专辑封面"><div><p>${state.playing?'正在播放':'上次听到这里'}</p><h2 class="track-title">${s.name}</h2><p>${s.artist}</p><button class="primary" data-action="resume">${state.playing?'进入播放':'继续播放'}</button><p>${time(state.progress)} / 4:12</p></div></section><div class="entries">${[['playlists','歌单列表','list','我的歌单与各平台精选'],['favorites','我的收藏','heart',`${state.favorites.size} 首喜欢的歌`],['settings','系统设置','settings','账号、播放与存储']].map(([id,name,i,sub])=>`<button class="entry" data-action="go:${id}">${icon(i)}<h3>${name}</h3><p>${sub}</p></button>`).join('')}</div><section class="recent"><h3>最近听过</h3><div class="recent-items">${tracks.slice(0,3).map((s,i)=>`<button data-action="track:${i}"><img src="${art(s.cover)}" alt=""><span>${s.name}<p>${s.artist}</p></span></button>`).join('')}</div></section></div>`}
const lines=['让风带走今天的心事','听见一段熟悉的旋律','把喜欢的歌留在身边','晚风轻轻吹过窗前','每一刻都值得被听见','从这里开始下一首歌'];
function player(){const s=current();return `<div class="player"><section class="record"><img class="record-art" src="${art(s.cover)}" alt="专辑封面"><div class="record-info"><h2 class="track-title">${s.name}</h2><p>${s.artist}</p><span class="source">QQ音乐 · 可播放</span>${ib('heart',`fav:${state.current}`,'收藏当前歌曲',`heart ${state.favorites.has(state.current)?'selected':''}`)}</div></section><div class="lyrics" aria-label="歌曲歌词">${lines.map((line,i)=>`<button data-action="lyric:${i*30}" class="${Math.floor(state.progress/30)%lines.length===i?'active':''}">${line}</button>`).join('')}</div><div class="transport"><div class="seek"><span>${time(state.progress)}</span><input aria-label="播放进度" type="range" max="252" value="${state.progress}" id="seek"><span>4:12</span></div><div class="transport-buttons">${ib(['order','shuffle','single','repeat'][state.mode],'mode',['顺序播放','随机播放','单曲循环','列表循环'][state.mode])}<div class="central-controls">${ib('prev','prev','上一首')}${ib(state.playing?'pause':'play','play',state.playing?'暂停':'播放','play')}${ib('next','next','下一首')}</div>${ib('list','queue','打开播放队列')}</div></div></div>`}
function songRows(items=tracks){return `<div class="rows">${items.map(s=>{const i=tracks.indexOf(s);return `<div class="song">${state.multi?`<input type="checkbox" aria-label="选择 ${s.name}">`:''}<img src="${art(s.cover)}" alt=""><button class="song-info" data-action="track:${i}"><span class="track-title">${s.name}</span><small>${s.artist}</small><small>QQ音乐 · 可播放</small></button>${ib('heart',`fav:${i}`,'收藏 '+s.name,`heart ${state.favorites.has(i)?'selected':''}`)}${ib('list',`song-menu:${i}`,'歌曲操作 '+s.name)}</div>`}).join('')}</div>`}
function detail(favorite=false){return `<div class="song-list"><div class="toolbar">${favorite?'':`<button data-action="go:playlists">返回歌单</button>`}<h3>${favorite?'我喜欢的音乐':'日常循环'}</h3><button class="primary" data-action="all">播放全部</button><button data-action="multi">${state.multi?'完成选择':'多选'}</button>${state.multi?'<button data-action="batch-download">下载所选</button><button data-action="collection">加入本地歌单</button>':''}</div>${songRows(favorite?tracks.filter((_,i)=>state.favorites.has(i)):tracks)}</div>`}
function library(){return `<div class="library"><div class="tabs">${['本地歌单','QQ音乐','网易云音乐','酷我音乐','汽水音乐'].map(x=>`<button class="${state.platform===x?'active':''}" data-action="platform:${x}">${x}</button>`).join('')}</div><div class="library-body"><div class="section-nav"><button class="active" data-action="mine">我的歌单</button><button data-action="recommended">推荐歌单</button><button data-action="collection">新建歌单</button></div><div class="playlist-grid">${groups.map(([name,owner,cover])=>`<button class="playlist-card" data-action="go:detail"><img src="${art(cover)}" alt="${name}"><h3>${name}</h3><p>${owner}</p></button>`).join('')}</div></div></div>`}
function search(){return `<div class="search"><div class="search-controls">${wide()?'':searchInput()}<div class="search-filter"><div class="tabs">${['歌曲','歌单','专辑'].map((x,i)=>`<button class="${i?'':'active'}" data-action="kind:${x}">${x}</button>`).join('')}</div><button data-action="sources">音源 · 3</button><button class="source-status" data-action="source-status">3 / 3 可用</button><button data-action="multi">${state.multi?'完成选择':'多选'}</button></div></div><div class="song-list">${songRows()}</div></div>`}
const sections=['播放与显示','平台账号','常规','下载与存储','WebDAV 同步','高级选项','关于'];
const toggle=name=>`<label class="setting-row"><span>${name}</span><input type="checkbox" aria-label="${name}"></label>`;
function settings(){let content='';if(state.section==='播放与显示')content=`<div class="setting-row"><span>主题</span><select id="theme-select" aria-label="主题">${['跟随系统','日间','夜间'].map((x,i)=>`<option value="${['system','day','night'][i]}" ${state.theme===['system','day','night'][i]?'selected':''}>${x}</option>`).join('')}</select></div>${['启动后自动播放','通知栏播放控制','黑胶封面'].map(toggle).join('')}`;else if(state.section==='平台账号')content=`<div class="tabs"><button class="active">QQ音乐</button><button>网易云音乐</button><button>汽水音乐</button></div><p>尚未关联账号</p><button class="primary" data-action="qr">扫码关联</button><button data-action="manual">手动关联（高级）</button>`;else if(state.section==='关于')content='<h3>星河音乐 v1.5.0</h3><p>让好音乐，随心而听。</p><p>功能来源：<a href="https://github.com/guohuiyuan/go-music-dl">GoMusicDll</a></p><p><a href="https://github.com/liangle902/CarMusic">星河音乐 · GitHub</a></p>';else if(state.section==='高级选项')content=`${['GitHub 代理','更换视频封面','更换音频','导出视频'].map(toggle).join('')}<button data-action="go:video">音乐视频制作</button>`;else if(state.section==='下载与存储')content=`${['下载嵌入封面与歌词','播放时自动缓存','自动扫描本地音乐与U盘'].map(toggle).join('')}<button data-action="go:local">本地音乐</button><button data-action="go:downloads">下载管理</button>`;else content=['失效音源自动换源','自动检查更新','启用 WebDAV 同步'].map(toggle).join('');return `<div class="settings"><div class="section-nav">${sections.map(x=>`<button class="${state.section===x?'active':''}" data-action="section:${x}">${x}</button>`).join('')}</div><div class="settings-content"><h3>${state.section}</h3>${content}</div></div>`}
function files(){return `<div class="song-list"><div class="toolbar">${state.page==='local'?'<button data-action="scan">扫描音乐</button><button data-action="import">添加目录 / U盘</button><button data-action="import">导入文件</button>':'<button>已完成</button><button>任务记录</button><button data-action="refresh">刷新</button>'}</div>${songRows()}</div>`}
function queue(){modal(`播放队列 · ${state.queue.length}`,`<p>拖动右侧手柄调整顺序，移除不会修改原歌单。</p>${state.queue.map((id,i)=>`<div class="queue-row" data-id="${id}" draggable="true"><span>${i+1}</span><button class="song-info" data-action="queue-track:${id}"><span class="track-title">${tracks[id].name}</span><small>${tracks[id].artist}</small></button>${ib('close',`remove:${id}`,'移出队列 '+tracks[id].name)}${ib('grip','drag','调整顺序','grip')}</div>`).join('')}`);let dragged;document.querySelectorAll('.queue-row').forEach(row=>{row.ondragstart=()=>{dragged=Number(row.dataset.id);row.classList.add('dragging')};row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();const id=Number(row.dataset.id);state.queue.splice(state.queue.indexOf(dragged),1);state.queue.splice(state.queue.indexOf(id),0,dragged);close();queue()}})}
const wide=()=>innerWidth>=600&&innerWidth>innerHeight;
const searchInput=()=>`<input class="search-input" value="${esc(state.query)}" aria-label="歌曲、歌手或分享链接" placeholder="歌曲、歌手或分享链接"><button class="primary" data-action="search">搜索</button>`;
function render(){const horizontal=wide();document.body.classList.toggle('horizontal',horizontal);document.getElementById('header-extra').innerHTML=horizontal?(state.page==='search'?searchInput():`<span class="header-slogan">${({home:'让好音乐，随心而听。',playlists:'一张歌单，一份心情',favorites:'喜欢的歌，都在这里'})[state.page]||''}</span>`):'';document.getElementById('navigation').innerHTML=pages.map(([id,name,i])=>`<button data-action="go:${id}" class="${state.page===id?'active':''}" aria-label="${name}">${icon(i)}<span class="nav-label">${name}</span></button>`).join('');document.getElementById('heading').textContent=pages.find(p=>p[0]===state.page)?.[1]||({'detail':'歌单','video':'视频制作'}[state.page]);document.getElementById('content').innerHTML=state.page==='home'?home():state.page==='playing'?player():state.page==='playlists'?library():state.page==='favorites'?detail(true):state.page==='detail'?detail():state.page==='search'?search():state.page==='settings'?settings():state.page==='video'?'<div class="settings-content"><div class="toolbar"><button data-action="material">更换封面 / 背景</button><button data-action="material">更换音频</button><button data-action="material">导入歌词</button><button data-action="export">制作视频</button></div><p>画面比例</p><select aria-label="画面比例"><option>16:9</option><option>9:16</option><option>1:1</option></select></div>':files();const s=current();document.getElementById('mini').innerHTML=['home','playing'].includes(state.page)?'':`<div><button class="song-info" data-action="go:playing"><span class="track-title">${s.name}</span></button></div>${ib(state.playing?'pause':'play','play',state.playing?'暂停':'播放')}${ib('list','queue','打开播放队列')}`}
function go(page){state.page=page;history.replaceState(null,'','#'+page);render()}
function theme(mode){state.theme=mode;document.body.classList.toggle('day',mode==='day'||mode==='system'&&matchMedia('(prefers-color-scheme:light)').matches)}
document.getElementById('collapse').onclick=()=>{const rail=document.querySelector('.rail'),expanded=rail.classList.toggle('expanded');document.getElementById('collapse').innerHTML=icon(expanded?'left':'right');document.getElementById('collapse').setAttribute('aria-expanded',String(expanded));document.getElementById('collapse').setAttribute('aria-label',expanded?'收起侧栏':'展开侧栏')};document.getElementById('collapse').innerHTML=icon('right');document.getElementById('theme').innerHTML=icon('sun');document.getElementById('theme').onclick=()=>{theme(state.theme==='day'?'night':'day');render()};document.getElementById('close-dialog').innerHTML=icon('close');document.getElementById('close-dialog').onclick=close;
document.addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(!target)return;const [a,value]=target.dataset.action.split(':');switch(a){case'go':go(value);return;case'resume':state.playing=true;go('playing');return;case'play':state.playing=!state.playing;break;case'prev':case'next':state.current=state.queue[(state.queue.indexOf(state.current)+(a==='next'?1:-1)+state.queue.length)%state.queue.length];state.progress=0;break;case'mode':state.mode=(state.mode+1)%4;break;case'fav':state.favorites.has(+value)?state.favorites.delete(+value):state.favorites.add(+value);break;case'track':state.current=+value;state.queue=[+value,...state.queue.filter(x=>x!==+value)];state.playing=true;go('playing');return;case'queue-track':state.current=+value;state.playing=true;close();go('playing');return;case'all':state.queue=state.page==='favorites'?[...state.favorites]:tracks.map((_,i)=>i);state.current=state.queue[0]??0;state.playing=true;go('playing');return;case'queue':queue();return;case'remove':state.queue=state.queue.filter(x=>x!==+value);if(state.current===+value)state.current=state.queue[0]??0;close();queue();return;case'section':state.section=value;break;case'platform':state.platform=value;break;case'multi':state.multi=!state.multi;break;case'lyric':state.progress=+value;break;case'qr':modal('扫码关联',`<div class="qr">${icon('qr')}</div><p>请使用对应平台 App 扫码</p><button data-action="refresh">检查登录状态</button>`);return;case'manual':modal('手动关联',`<input aria-label="Cookie" type="password" placeholder="Cookie"><button data-action="close">关闭</button>`);return;case'song-menu':modal(tracks[+value].name,`<button data-action="collection">加入本地歌单</button><button data-action="source-dialog">切换音源</button><button data-action="batch-download">下载音乐</button>`);return;case'sources':modal('选择搜索音源',`<div class="tabs source-options">${['QQ音乐','网易云音乐','酷我音乐','酷狗音乐','汽水音乐','Bilibili'].map((name,i)=>`<button data-action="source:${name}" class="${i<3?'active':''}">${i<3?'✓ ':''}${name}</button>`).join('')}</div><button data-action="close">完成</button>`);return;case'source-status':modal('搜索源状态','<p>QQ音乐 · 搜索可用</p><p>网易云音乐 · 搜索可用</p><p>酷我音乐 · 搜索可用</p>');return;case'source-dialog':modal('切换音源','<button data-action="refresh">网易云音乐</button><button data-action="refresh">酷我音乐</button>');return;case'collection':modal('本地歌单','<input aria-label="歌单名称" placeholder="歌单名称"><button data-action="close">保存</button>');return;case'close':close();return;case'kind':case'source':target.classList.toggle('active');return;case'search':toast('搜索结果已更新');return;case'drag':return;case'mine':case'recommended':target.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));target.classList.add('active');return;case'import':case'material':modal('选择文件','<input aria-label="文件" type="file" accept="audio/*,image/*">');return;default:toast({scan:'扫描完成',refresh:'已刷新','batch-download':'已加入下载任务',export:'已加入制作任务'}[a]||'已保存');return}render()});
document.addEventListener('change',e=>{if(e.target.id==='theme-select'){theme(e.target.value);render()}if(e.target.id==='seek'){state.progress=+e.target.value;render()}});
window.addEventListener('hashchange',()=>{state.page=location.hash.slice(1)||'home';render()});state.page=location.hash.slice(1)||'home';theme('system');render();

window.addEventListener('resize',render);document.addEventListener('input',e=>{if(e.target.classList.contains('search-input'))state.query=e.target.value});
